### ISSUE TITLE
Sample rate discrepancy.

### ISSUE THREAD

**Issue by kuper-dot** [massej/RadioHLSConverter.backend.serverless#5]
It is slightly strange, but I can use VLC and Chrome to playback HTTP streams. However, when I put this link into application that uses Mp3FileReader I get the following error: "Got a frame at sample rate X, in an MP3 with sample rate 44100. Mp3FiieReader does not support sample rate changes."

I have no way of changing the source code of the said application, so my only hope is that someone will help me reconfigure HLSConverter. Thanks

**Comment by massej** [comment]
Hi, @kuper-dot do you have the radio link URL, I will try to replicate the issue

**Comment by kuper-dot** [comment]
@massej 
Yep, here is the direct m3u8 link:
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_world_service/bbc_world_service.isml/bbc_world_service-audio%3d96000.norewind.m3u8

And this is a file where it came from:
http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/ak/bbc_world_service.m3u8

Thanks for helping out.

**Comment by massej** [comment]
Thank you @kuper-dot I was not able to replicate the issue using the Radio HLS converter, on my side I was able to listen the BBC World Service radio without any issue.

Can you send me your application logs file? I was not able to find any Mp3FileReader reference inside the Radio HLS converter

**Comment by kuper-dot** [comment]
Hello, thanks for your help @massej. Turns out that the only issue here is with me. I forgot to change FFMPEGConverterAudioCodec from copy to mp3, which resulted in MP3FileReader's inability to read this stream, changing it to mp3 fixed this issue. 

Now everything works like a charm. Thank you very much for helping out, and for this beautiful tool ;)

**Comment by massej** [comment]
Thank you @kuper-dot for letting me know, that make sense,

I just released a new version 1.17 with the latest ffmpeg 6.0,

It also fix the issue with absolute path that had the link http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/ak/bbc_world_service.m3u8

You should now be able to use http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/ak/bbc_world_service.m3u8 in the config file.

Don't be shy to let me know if you find any other issue,

Best,
